
services:
  # disable for mac users and install native with GPU
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    # runtime: nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - autism
    ports:
      - "11434:11434"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    # Disable for Mac users with GPU usage
    depends_on: [ollama]
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434 # For Mac users with GPU usage
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - autism
    ports:
      - "3000:8080"
    restart: unless-stopped

volumes:
  ollama_models:
  openwebui_data:
  mongodb_data:

networks:
  autism:
    name: autism
    driver: bridge